# Generated by `brew generate-tap-man-completions`.
__fish_brew_complete_cmd 'generate-tap-man-completions' 'Generate shell completions and man pages for a tap\'s commands'
__fish_brew_complete_arg 'generate-tap-man-completions' -l debug -d 'Display any debugging information'
__fish_brew_complete_arg 'generate-tap-man-completions' -l help -d 'Show this message'
__fish_brew_complete_arg 'generate-tap-man-completions' -l no-exit-code -d 'Exit with code 0 even if no changes were made'
__fish_brew_complete_arg 'generate-tap-man-completions' -l quiet -d 'Make some output more quiet'
__fish_brew_complete_arg 'generate-tap-man-completions' -l tap -d 'Generate completions for tap (default: auto-detected from command location)'
__fish_brew_complete_arg 'generate-tap-man-completions' -l verbose -d 'Make some output more verbose'
