# Generated by `brew generate-tap-man-completions`.
__fish_brew_complete_cmd 'man' 'Display a man page bundled with an installed formula'
__fish_brew_complete_arg 'man' -l debug -d 'Display any debugging information'
__fish_brew_complete_arg 'man' -l help -d 'Show this message'
__fish_brew_complete_arg 'man' -l html -d 'Render the man page as HTML and open it in a browser (respects `HOMEBREW_BROWSER` or `BROWSER`)'
__fish_brew_complete_arg 'man' -l interactive -d 'Interactively resolve ambiguity when multiple copies of a man page are found'
__fish_brew_complete_arg 'man' -l list -d 'List all locations where the named man page is found'
__fish_brew_complete_arg 'man' -l quiet -d 'Make some output more quiet'
__fish_brew_complete_arg 'man' -l verbose -d 'Make some output more verbose'
