# Generated by `brew generate-tap-man-completions`.
__fish_brew_complete_cmd 'purge-quarantine' 'Disables macOS\'s Gatekeeper for the named casks by removing the `com.apple.quarantine` and `com.apple.provenance` extended attributes from their installed macOS bundles (`.app`, `.component`, `.colorPicker`, `.saver`, `.webplugin`, and other artifact types)'
__fish_brew_complete_arg 'purge-quarantine' -l debug -d 'Display any debugging information'
__fish_brew_complete_arg 'purge-quarantine' -l help -d 'Show this message'
__fish_brew_complete_arg 'purge-quarantine' -l quiet -d 'Make some output more quiet'
__fish_brew_complete_arg 'purge-quarantine' -l verbose -d 'Make some output more verbose'
__fish_brew_complete_arg 'purge-quarantine' -a '(__fish_brew_suggest_casks_installed)'
