# SPDX-FileCopyrightText: Copyright 2026 Todd Schulman
#
# SPDX-License-Identifier: GPL-3.0-or-later OR BSD-2-Clause

# Generated by `brew generate-tap-completions`.
__fish_brew_complete_cmd 'purge-quarantine' 'Disables macOS\'s Gatekeeper for the named casks by removing the `com.apple.quarantine` and `com.apple.provenance` extended attributes from their installed macOS bundles'
__fish_brew_complete_arg 'purge-quarantine' -l debug -d 'Display debug information'
__fish_brew_complete_arg 'purge-quarantine' -l help -d 'Show this message'
__fish_brew_complete_arg 'purge-quarantine' -l quiet -d 'Suppress any warnings'
__fish_brew_complete_arg 'purge-quarantine' -l verbose -d 'Make some output more verbose'
__fish_brew_complete_arg 'purge-quarantine' -a '(__fish_brew_suggest_casks_installed)'
