# SPDX-FileCopyrightText: Copyright 2026 Todd Schulman
#
# SPDX-License-Identifier: GPL-3.0-or-later OR BSD-2-Clause

# typed: strict
# frozen_string_literal: true

require "abstract_command"
require "completions"
require "system_command"
require "tap"

module Homebrew
  module DevCmd
    # Generates shell completions for this tap's external commands.
    class GenerateTapCompletions < AbstractCommand
      include SystemCommand::Mixin

      cmd_args do
        description <<~EOS
          Generate shell completions for this tap's commands.
        EOS

        switch "--no-exit-code", description: "Exit with code 0 even if no changes were made."
        named_args :none
      end

      TAP_NAME = T.let("toobuntu/cask-tools", String)
      HEADER = T.let("# Generated by `brew generate-tap-completions`.\n", String)

      sig { override.void }
      def run
        tap_path = Tap.fetch(TAP_NAME).path
        bash_dir = tap_path/"completions/bash"
        zsh_dir  = tap_path/"completions/zsh"
        fish_dir = tap_path/"completions/fish"
        [bash_dir, zsh_dir, fish_dir].each(&:mkpath)

        Pathname.glob(tap_path/"cmd/*.rb").sort.each do |cmd_path|
          command = cmd_path.basename(".rb").to_s
          write_if_changed bash_dir/"brew-#{command}",      bash_content(command)
          write_if_changed zsh_dir/"_brew-#{command}",      zsh_content(command)
          write_if_changed fish_dir/"brew-#{command}.fish", fish_content(command)
        end

        diff = system_command "git", args: [
          "-C", tap_path,
          "diff", "--shortstat", "--patch", "--exit-code", "completions"
        ]

        if diff.status.success?
          ofail "No changes to completions." unless args.no_exit_code?
        else
          puts "Completions updated."
        end
      end

      private

      sig { params(path: Pathname, content: String).void }
      def write_if_changed(path, content)
        return if path.exist? && path.read == content

        path.write(content)
      end

      sig { params(command: String).returns(String) }
      def bash_content(command)
        func = Completions.generate_bash_subcommand_completion(command) ||
               "_brew_#{command.tr("-", "_")}() { : ; }\n"
        HEADER + func
      end

      sig { params(command: String).returns(String) }
      def zsh_content(command)
        func = Completions.generate_zsh_subcommand_completion(command) ||
               "_brew_#{command.tr("-", "_")}() { : ; }\n"
        HEADER + func
      end

      sig { params(command: String).returns(String) }
      def fish_content(command)
        func = Completions.generate_fish_subcommand_completion(command) ||
               "__fish_brew_complete_cmd '#{command}' '#{command}'\n"
        HEADER + func
      end
    end
  end
end
