# SPDX-FileCopyrightText: Copyright 2026 Todd Schulman
#
# SPDX-License-Identifier: GPL-3.0-or-later OR BSD-2-Clause

# typed: strict
# frozen_string_literal: true

require "abstract_command"
require "system_command"
require "tap"

module Homebrew
  module Cmd
    # Generates shell completions and man pages for a tap's external commands.
    class GenerateTapManCompletions < AbstractCommand
      include SystemCommand::Mixin

      cmd_args do
        usage_banner "`generate-tap-man-completions` [`--tap=`<tap>] [`--no-exit-code`]"
        description <<~EOS
          Generate shell completions and man pages for a tap's commands.

          Reads each `*.rb` file in `cmd/` and writes Bash, ZSH, and Fish completion
          files into `completions/`, and Ronn man page sources (`.1.md`) and compiled
          roff (`.1`) into `manpages/`. The tap is auto-detected from the location of
          this command file. Use `--tap` to override.
        EOS

        flag   "--tap=",
               description: "Generate completions for <tap> (default: auto-detected from command location)."
        switch "--no-exit-code",
               description: "Exit with code 0 even if no changes were made."
        named_args :none
      end

      HEADER = T.let("# Generated by `brew generate-tap-man-completions`.\n", String)

      sig { override.void }
      def run
        unless Homebrew::EnvConfig.developer?
          raise UsageError, "`brew generate-tap-man-completions` is a developer command. " \
                            "Set HOMEBREW_DEVELOPER=1 to enable it."
        end

        tap = resolve_tap
        tap_path = tap.path
        bash_dir = tap_path/"completions/bash"
        zsh_dir  = tap_path/"completions/zsh"
        fish_dir = tap_path/"completions/fish"
        man_dir  = tap_path/"manpages"
        [bash_dir, zsh_dir, fish_dir, man_dir].each(&:mkpath)

        # kramdown (man bundler group) is needed to compile Ronn sources to roff
        Homebrew.install_bundler_gems!(groups: ["man"])
        require "manpages/parser/ronn"
        require "manpages/converter/roff"

        dev_cmd_names = Pathname.glob(tap_path/"dev-cmd/*.rb").to_set { |p| p.basename(".rb").to_s }
        cmd_paths = Pathname.glob(tap_path/"cmd/*.rb").reject do |p|
          dev_cmd_names.include?(p.basename(".rb").to_s)
        end
        cmd_paths.sort.each do |cmd_path|
          command = cmd_path.basename(".rb").to_s
          parser = Homebrew::CLI::Parser.from_cmd_path(cmd_path)

          write_if_changed bash_dir/"brew-#{command}",      bash_completion(command, parser)
          write_if_changed zsh_dir/"_brew-#{command}",      zsh_completion(command, parser)
          write_if_changed fish_dir/"brew-#{command}.fish", fish_completion(command, parser)

          md = man_page_markdown(command, parser)
          next unless md

          write_if_changed man_dir/"brew-#{command}.1.md", md
          roff, = T.unsafe(Homebrew)::Manpages::Converter::Roff.convert(
            T.unsafe(Homebrew)::Manpages::Parser::Ronn.parse(md).first,
          )
          write_if_changed man_dir/"brew-#{command}.1", roff if roff
        end

        diff = system_command "git", args: [
          "-C", tap_path,
          "diff", "--shortstat", "--patch", "--exit-code", "completions", "manpages"
        ]

        message = if diff.status.success?
          "No changes to completions or man pages."
        else
          "Completions and man pages updated."
        end
        if diff.status.success? && !args.no_exit_code?
          ofail message
        else
          puts message
        end
      end

      private

      sig { returns(Tap) }
      def resolve_tap
        if (tap_arg = args.tap)
          Tap.fetch(tap_arg)
        else
          tap_dir = Pathname(__FILE__).dirname.dirname
          # Prefer direct match (fast path comparison, no I/O).
          tap = Tap.all.find { |t| t.path == tap_dir }
          # Fallback: command is hardlinked into Homebrew's core cmd/ (e.g., CI);
          # find the tap that has this command in its dev-cmd/ directory.
          tap ||= Tap.all.find { |t| (t.path/"dev-cmd/#{File.basename(__FILE__, ".rb")}.rb").exist? }
          T.must_because(tap) do
            "Could not auto-detect tap from #{tap_dir}. Use --tap=<user>/<repo>."
          end
        end
      end

      sig { params(path: Pathname, content: String).void }
      def write_if_changed(path, content)
        return if path.exist? && path.read == content

        path.write(content)
      end

      sig { params(parser: Homebrew::CLI::Parser).returns(T::Hash[String, String]) }
      def expanded_options(parser)
        options = {}
        parser.processed_options.each do |short, long, desc, hidden|
          next if hidden

          name = T.must(long || short)
          if name.start_with?("--[no-]")
            options[name.gsub("[no-]", "")] = desc
            options[name.sub("[no-]", "no-")] = desc
          else
            options[name] = desc
          end
        end
        options
      end

      # Formats a description string for shell completions, matching
      # the escaping behaviour of Homebrew::Completions.format_description.
      sig { params(text: String, fish: T::Boolean).returns(String) }
      def escape_description(text, fish: false)
        result = if fish
          text.gsub("'", "\\\\'")
        else
          text.gsub("'", "'\\\\''")
        end
        result.gsub(/[<>]/, "").tr("\n", " ").chomp(".")
      end

      sig { params(command: String, parser: T.nilable(Homebrew::CLI::Parser)).returns(String) }
      def bash_completion(command, parser)
        func_name = command.tr("-", "_").delete("?")
        options = parser && expanded_options(parser)
        if options&.any?
          HEADER + <<~COMPLETION
            _brew_#{func_name}() {
              local cur="${COMP_WORDS[COMP_CWORD]}"
              case "${cur}" in
                -*)
                  __brewcomp "
                  #{options.keys.sort.join("\n      ")}
                  "
                  return
                  ;;
                *) ;;
              esac
            }
          COMPLETION
        else
          HEADER + "_brew_#{func_name}() { : ; }\n"
        end
      end

      sig { params(command: String, parser: T.nilable(Homebrew::CLI::Parser)).returns(String) }
      def zsh_completion(command, parser)
        func_name = command.tr("-", "_").delete("?")
        options = parser && expanded_options(parser)
        if options&.any?
          opts = options.sort.map do |opt, desc|
            if desc.blank?
              "'#{opt}'"
            else
              "'#{opt}[#{escape_description(desc)}]'"
            end
          end
          HEADER + <<~COMPLETION
            # brew #{command}
            _brew_#{func_name}() {
              _arguments \\
                #{opts.join(" \\\n    ")}
            }
          COMPLETION
        else
          HEADER + "_brew_#{func_name}() { : ; }\n"
        end
      end

      sig { params(command: String, parser: T.nilable(Homebrew::CLI::Parser)).returns(String) }
      def fish_completion(command, parser)
        options = parser && expanded_options(parser)
        if options&.any?
          short_desc = T.must(parser).description&.split(/\.(?>\s|$)/)&.first
          desc_text = escape_description(short_desc.to_s, fish: true)
          lines = ["__fish_brew_complete_cmd '#{command}' '#{desc_text}'"]
          options.sort.each do |opt, desc|
            line = "__fish_brew_complete_arg '#{command}' -l #{opt.sub(/^-+/, "")}"
            line += " -d '#{escape_description(desc, fish: true)}'" if desc.present?
            lines << line
          end
          HEADER + "#{lines.join("\n")}\n"
        else
          HEADER + "__fish_brew_complete_cmd '#{command}' '#{command}'\n"
        end
      end

      sig { params(command: String, parser: T.nilable(Homebrew::CLI::Parser)).returns(T.nilable(String)) }
      def man_page_markdown(command, parser)
        return unless parser

        banner = parser.usage_banner_text
        return unless banner

        # usage_banner_text contains synopsis followed by description, separated by one or more blank lines
        parts = banner.strip.split(/\n\n+/, 2)
        synopsis = parts[0]&.strip
        return unless synopsis

        description = parts[1]&.strip

        # Use description's first line as the title suffix when it is a complete sentence
        lines = description&.lines
        first_line = lines&.first&.strip
        short_desc = first_line&.end_with?(".") ? first_line.delete_suffix(".") : nil

        title_cmd = "brew-#{command}"
        title_line = short_desc ? "#{title_cmd}(1) -- #{short_desc}" : "#{title_cmd}(1)"

        md = "#{title_line}\n#{"=" * title_line.length}\n\n"
        md << "## SYNOPSIS\n\n`brew` #{synopsis}\n\n"
        md << "## DESCRIPTION\n\n#{description}\n\n" if description
        md << "## OPTIONS\n\n"
        parser.processed_options.each do |opt|
          short, long, desc, hidden = opt
          next if hidden

          opt_parts = [short && "`#{short}`", long && "`#{long}`"].compact
          md << "#{opt_parts.join(", ")}\n\n: #{desc}\n\n"
        end

        md.freeze
      end
    end
  end
end
