# SPDX-FileCopyrightText: Copyright 2026 Todd Schulman
#
# SPDX-License-Identifier: GPL-3.0-or-later OR BSD-2-Clause

# typed: strict
# frozen_string_literal: true

require "abstract_command"
require "completions"
require "system_command"
require "tap"

module Homebrew
  module Cmd
    # Generates shell completions and man pages for a tap's external commands.
    class GenerateTapManCompletions < AbstractCommand
      include SystemCommand::Mixin

      cmd_args do
        usage_banner "`generate-tap-man-completions` [`--tap=`<tap>] [`--no-exit-code`]"
        description <<~EOS
          Generate shell completions and man pages for a tap's commands.

          Reads each `*.rb` file in `cmd/` and `dev-cmd/` and writes Bash, ZSH, and
          Fish completion files into `completions/`, and Ronn man page sources (`.1.md`)
          and compiled roff (`.1`) into `manpages/`. Stale files for removed commands are
          cleaned up automatically. The tap is auto-detected from the location of this
          command file. Use `--tap` to override.

          Exits non-zero when no files change (like `git diff --exit-code`). This is the
          same convention used by Homebrew's `generate-man-completions`. Pass
          `--no-exit-code` to always exit 0.

          Pass `--debug` for detailed diagnostics about tap resolution, command
          discovery, and per-file write decisions.
        EOS

        flag   "--tap=",
               description: "Generate completions for <tap> (default: auto-detected from command location)."
        switch "--no-exit-code",
               description: "Exit with code 0 even if no changes were made."
        named_args :none
      end

      HEADER = T.let("# Generated by `brew generate-tap-man-completions`.\n", String)

      sig { override.void }
      def run
        unless Homebrew::EnvConfig.developer?
          raise UsageError, "`brew generate-tap-man-completions` is a developer command. " \
                            "Set HOMEBREW_DEVELOPER=1 to enable it."
        end

        tap = resolve_tap
        tap_path = tap.path
        odebug "Tap: #{tap.name} (#{tap_path})"

        bash_dir = tap_path/"completions/bash"
        zsh_dir  = tap_path/"completions/zsh"
        fish_dir = tap_path/"completions/fish"
        man_dir  = tap_path/"manpages"
        [bash_dir, zsh_dir, fish_dir, man_dir].each(&:mkpath)

        # kramdown (man bundler group) is needed to compile Ronn sources to roff
        Homebrew.install_bundler_gems!(groups: ["man"])
        require "manpages/parser/ronn"
        require "manpages/converter/roff"

        cmd_paths = collect_command_paths(tap_path)

        if cmd_paths.empty?
          opoo "No commands found in #{tap.name} cmd/ or dev-cmd/."
          return
        end

        odebug "Commands: #{cmd_paths.map { |_name, p| p.basename(".rb") }.sort.join(", ")}"

        generated_commands = T.let([], T::Array[String])
        cmd_paths.sort.each do |command, cmd_path|
          odebug "Processing #{command} (#{cmd_path}):"
          write_if_changed bash_dir/"brew-#{command}",      bash_content(command)
          write_if_changed zsh_dir/"_brew-#{command}",      zsh_content(command)
          write_if_changed fish_dir/"brew-#{command}.fish", fish_content(command)

          md = man_page_markdown(command, cmd_path)
          if md.nil?
            odebug "  skip man page: no parser or usage banner for #{command}"
            generated_commands << command
            next
          end

          write_if_changed man_dir/"brew-#{command}.1.md", md
          roff, = T.unsafe(Homebrew)::Manpages::Converter::Roff.convert(
            T.unsafe(Homebrew)::Manpages::Parser::Ronn.parse(md).first,
          )
          write_if_changed man_dir/"brew-#{command}.1", roff if roff
          generated_commands << command
        end

        remove_stale_files(generated_commands, bash_dir:, zsh_dir:, fish_dir:, man_dir:)

        diff = system_command "git", args: [
          "-C", tap_path,
          "diff", "--shortstat", "--patch", "--exit-code", "completions", "manpages"
        ]

        message = if diff.status.success?
          "No changes to completions or man pages."
        else
          "Completions and man pages updated."
        end
        if diff.status.success? && !args.no_exit_code?
          ofail message
        else
          puts message
        end
      end

      private

      sig { returns(Tap) }
      def resolve_tap
        if (tap_arg = args.tap)
          odebug "Using --tap override: #{tap_arg}"
          Tap.fetch(tap_arg)
        else
          tap_dir = Pathname(__FILE__).dirname.dirname
          odebug "Auto-detecting tap from #{tap_dir}"
          # Prefer direct match (fast path comparison, no I/O).
          tap = Tap.all.find { |t| t.path == tap_dir }
          # Fallback: command is hardlinked into Homebrew's core cmd/ (e.g., CI);
          # find the tap that has this command in its dev-cmd/ directory.
          tap ||= Tap.all.find { |t| (t.path/"dev-cmd/#{File.basename(__FILE__, ".rb")}.rb").exist? }
          odebug "Resolved tap: #{tap&.name || "not found"}"
          T.must_because(tap) do
            "Could not auto-detect tap from #{tap_dir}. Use --tap=<user>/<repo>."
          end
        end
      end

      # Collect unique command paths from cmd/ and dev-cmd/.
      # When the same basename exists in both directories (e.g. a hardlink), prefer dev-cmd/.
      sig { params(tap_path: Pathname).returns(T::Array[[String, Pathname]]) }
      def collect_command_paths(tap_path)
        all = T.let({}, T::Hash[String, Pathname])
        Pathname.glob(tap_path/"cmd/*.rb").each { |p| all[p.basename(".rb").to_s] = p }
        Pathname.glob(tap_path/"dev-cmd/*.rb").each { |p| all[p.basename(".rb").to_s] = p }
        odebug "dev-cmd/ commands: #{Pathname.glob(tap_path/"dev-cmd/*.rb").map { |p| p.basename(".rb") }}" \
          if (tap_path/"dev-cmd").directory?
        all.to_a
      end

      # Remove stale completion and man page files whose commands no longer exist.
      sig {
        params(
          commands: T::Array[String],
          bash_dir: Pathname,
          zsh_dir:  Pathname,
          fish_dir: Pathname,
          man_dir:  Pathname,
        ).void
      }
      def remove_stale_files(commands, bash_dir:, zsh_dir:, fish_dir:, man_dir:)
        command_set = commands.to_set
        stale = T.let([], T::Array[Pathname])
        # Skip .license sidecars — they are managed by scripts/annotate.sh, not this generator.
        no_license = ->(p) { p.extname != ".license" }
        stale.concat(Pathname.glob(bash_dir/"brew-*").select(&no_license).reject do |p|
          command_set.include?(p.basename.to_s.delete_prefix("brew-"))
        end)
        stale.concat(Pathname.glob(zsh_dir/"_brew-*").select(&no_license).reject do |p|
          command_set.include?(p.basename.to_s.delete_prefix("_brew-"))
        end)
        stale.concat(Pathname.glob(fish_dir/"brew-*.fish").reject do |p|
          command_set.include?(p.basename(".fish").to_s.delete_prefix("brew-"))
        end)
        stale.concat(Pathname.glob(man_dir/"brew-*.1").reject do |p|
          command_set.include?(p.basename(".1").to_s.delete_prefix("brew-"))
        end)
        stale.concat(Pathname.glob(man_dir/"brew-*.1.md").reject do |p|
          command_set.include?(p.basename(".1.md").to_s.delete_prefix("brew-"))
        end)
        return if stale.empty?

        stale.sort.each do |path|
          odebug "  removing stale: #{path.basename}"
          path.delete
        end
      end

      sig { params(path: Pathname, content: String).void }
      def write_if_changed(path, content)
        if path.exist? && path.read == content
          odebug "  skip (unchanged): #{path.basename}"
          return
        end

        odebug "  write: #{path.basename}"
        path.write(content)
      end

      sig { params(command: String).returns(String) }
      def bash_content(command)
        func = Completions.generate_bash_subcommand_completion(command) ||
               "_brew_#{command.tr("-", "_")}() { : ; }\n"
        HEADER + func
      end

      sig { params(command: String).returns(String) }
      def zsh_content(command)
        func = Completions.generate_zsh_subcommand_completion(command) ||
               "_brew_#{command.tr("-", "_")}() { : ; }\n"
        HEADER + func
      end

      sig { params(command: String).returns(String) }
      def fish_content(command)
        func = Completions.generate_fish_subcommand_completion(command) ||
               "__fish_brew_complete_cmd '#{command}' '#{command}'\n"
        HEADER + func
      end

      sig { params(command: String, cmd_path: Pathname).returns(T.nilable(String)) }
      def man_page_markdown(command, cmd_path)
        parser = Homebrew::CLI::Parser.from_cmd_path(cmd_path)
        return unless parser

        banner = parser.usage_banner_text
        return unless banner

        # usage_banner_text contains synopsis followed by description, separated by one or more blank lines
        parts = banner.strip.split(/\n\n+/, 2)
        synopsis = parts[0]&.strip
        return unless synopsis

        description = parts[1]&.strip

        # Use description's first line as the title suffix when it is a complete sentence
        lines = description&.lines
        first_line = lines&.first&.strip
        short_desc = first_line&.end_with?(".") ? first_line.delete_suffix(".") : nil

        title_cmd = "brew-#{command}"
        title_line = short_desc ? "#{title_cmd}(1) -- #{short_desc}" : "#{title_cmd}(1)"

        md = "#{title_line}\n#{"=" * title_line.length}\n\n"
        md << "## SYNOPSIS\n\n`brew` #{synopsis}\n\n"
        md << "## DESCRIPTION\n\n#{description}\n\n" if description
        md << "## OPTIONS\n\n"
        parser.processed_options.each do |opt|
          short, long, desc, hidden = opt
          next if hidden

          opt_parts = [short && "`#{short}`", long && "`#{long}`"].compact
          md << "#{opt_parts.join(", ")}\n\n: #{desc}\n\n"
        end

        md.freeze
      end
    end
  end
end
