name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  style:
    name: brew style
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew style ./cmd/purge-quarantine.rb
